version = 3.11.3
runner.dialect = scala3Future
preset = IntelliJ
maxColumn = 120
align.preset = more
align.multiline = false
docstrings.wrap = fold
newlines.source = keep
rewrite.trailingCommas.style = keep
rewrite.rules = [SortModifiers]
optIn.configStyleArguments = true
